name: Release

on:
  push:
    branches:
      - main
    paths:
      - psh2bat/version.py
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3

      - name: Install Dependences
        shell: bash
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
          PIP_DISABLE_PIP_VERSION_CHECK: 1
          PIP_NO_WARN_SCRIPT_LOCATION: 0
        run: |
          python -m pip install build twine --upgrade

      - name: Build Wheel
        shell: bash
        run: |
          python -m build "${{ github.workspace }}" --outdir "${{ github.workspace }}/dist"

      - name: Upload to PyPI
        shell: bash
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python -m twine upload "${{ github.workspace }}/dist"/*

      - name: Create Github release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          psh2bat_version=$(python -c "from psh2bat.version import VERSION; print(VERSION)")
          previous_tag=$(gh release view --json tagName --jq '.tagName')
          gh release create "v${psh2bat_version}" "${{ github.workspace }}/dist"/* \
            --target main \
            --generate-notes \
            --title "Release v${psh2bat_version}" # \
            # --notes-start-tag "${previous_tag}"
